var data = [
    {
        "spt_name": "B1",
        "dept_to_water": 5,
        "name" : 'test 1',
        "lat": -37.8210922667,
        "lng": 175.2209316333,
        "type": TEST_TYPES.SP1,
        "samples": [
            {
                "elevation": 892.2,
                "sample_no": "S-01",
                "uscs": "MH",
                "weight": 120,
                "depth_to_top": 0,
                "depth_to_bottom": 2,
                "depth_to_midpoint": 1,
                "pressure1": 120,
                "u": 0,
                "pressure2": 120,
                "blows": 7
            },
            {
                "elevation": 890.2,
                "sample_no": "S-02",
                "uscs": "CL",
                "weight": 120,
                "depth_to_top": 2,
                "depth_to_bottom": 4,
                "depth_to_midpoint": 3,
                "pressure1": 360,
                "u": 0,
                "pressure2": 360,
                "blows": 6
            },
            {
                "elevation": 888.2,
                "sample_no": "S-03",
                "uscs": "CH",
                "weight": 120,
                "depth_to_top": 4,
                "depth_to_bottom": 6,
                "depth_to_midpoint": 5,
                "pressure1": 600,
                "u": 0,
                "pressure2": 600,
                "blows": 6
            },
            {
                "elevation": 886.2,
                "sample_no": "S-04",
                "uscs": "CL",
                "weight": 130,
                "depth_to_top": 6,
                "depth_to_bottom": 8,
                "depth_to_midpoint": 7,
                "pressure1": 910,
                "u": 124.8,
                "pressure2": 785.2,
                "blows": 26
            },
            {
                "elevation": 884.2,
                "sample_no": "S-05",
                "uscs": "PWR",
                "weight": 140,
                "depth_to_top": 8,
                "depth_to_bottom": 9.1,
                "depth_to_midpoint": 8.6,
                "pressure1": 1197,
                "u": 221.5,
                "pressure2": 975.5,
                "blows": 99
            }
        ]
    }, {
        "spt_name": "B2",
        "dept_to_water": 10,
        "name" : 'test 3',
        "lat": -37.8210881833,
        "lng": 175.2215004833,
        "type": TEST_TYPES.SP2,
        "samples": [
            {
                "elevation": 896.2,
                "sample_no": "S-01",
                "uscs": "CL",
                "weight": 120,
                "depth_to_top": 0,
                "depth_to_bottom": 2,
                "depth_to_midpoint": 1,
                "pressure1": 120,
                "u": 0,
                "pressure2": 120,
                "blows": 6
            },
            {
                "elevation": 894.2,
                "sample_no": "S-02",
                "uscs": "SC",
                "weight": 120,
                "depth_to_top": 2,
                "depth_to_bottom": 4,
                "depth_to_midpoint": 3,
                "pressure1": 360,
                "u": 0,
                "pressure2": 360,
                "blows": 7
            }
        ]
    },
    {
        "spt_name": "B3",
        "dept_to_water": 8,
        "name" : 'test 6',
        "lat": -37.8208292333,
        "lng": 175.2214374833,
        "type": TEST_TYPES.SP1,
        "samples": [
            {
                "elevation": 896.4,
                "sample_no": "S-01",
                "uscs": "SC",
                "weight": 120,
                "depth_to_top": 4,
                "depth_to_bottom": 6,
                "depth_to_midpoint": 5,
                "pressure1": 600,
                "u": 0,
                "pressure2": 600,
                "blows": 8
            },
            {
                "elevation": 890.4,
                "sample_no": "S-02",
                "uscs": "CL",
                "weight": 120,
                "depth_to_top": 6,
                "depth_to_bottom": 8,
                "depth_to_midpoint": 7,
                "pressure1": 840,
                "u": 0,
                "pressure2": 840,
                "blows": 5
            },
            {
                "elevation": 888.4,
                "sample_no": "S-03",
                "uscs": "CH",
                "weight": 125,
                "depth_to_top": 8,
                "depth_to_bottom": 10,
                "depth_to_midpoint": 9,
                "pressure1": 1125,
                "u": 62.4,
                "pressure2": 1062.6,
                "blows": 8
            },
            {
                "elevation": 886.4,
                "sample_no": "S-04",
                "uscs": "CH",
                "weight": 125,
                "depth_to_top": 10,
                "depth_to_bottom": 11.6,
                "depth_to_midpoint": 10.8,
                "pressure1": 1350,
                "u": 174.7,
                "pressure2": 1175.3,
                "blows": 11
            },
        ]
    }, {
        "spt_name": "B4",
        "dept_to_water": 5,
        "name" : 'test 5',
        "lat": -37.8209458667,
        "lng": 175.2214051333,
        "type": TEST_TYPES.OTHERS,       
        "samples": [
            {
                "elevation": 900.1,
                "sample_no": "S-01",
                "uscs": "CL",
                "weight": 120,
                "depth_to_top": 0,
                "depth_to_bottom": 2,
                "depth_to_midpoint": 1,
                "pressure1": 120,
                "u": 0,
                "pressure2": 120,
                "blows": 9
            },
            {
                "elevation": 898.1,
                "sample_no": "S-02",
                "uscs": "CL",
                "weight": 120,
                "depth_to_top": 2,
                "depth_to_bottom": 4,
                "depth_to_midpoint": 3,
                "pressure1": 360,
                "u": 0,
                "pressure2": 360,
                "blows": 4
            },
            {
                "elevation": 896.1,
                "sample_no": "S-03",
                "uscs": "CL",
                "weight": 125,
                "depth_to_top": 4,
                "depth_to_bottom": 6,
                "depth_to_midpoint": 5,
                "pressure1": 625,
                "u": 0,
                "pressure2": 625,
                "blows": 12
            },
            {
                "elevation": 894.1,
                "sample_no": "S-04",
                "uscs": "CL",
                "weight": 120,
                "depth_to_top": 6,
                "depth_to_bottom": 8,
                "depth_to_midpoint": 7,
                "pressure1": 840,
                "u": 124.8,
                "pressure2": 715.2,
                "blows": 6
            },
            {
                "elevation": 892.1,
                "sample_no": "S-05",
                "uscs": "ML",
                "weight": 120,
                "depth_to_top": 8,
                "depth_to_bottom": 10,
                "depth_to_midpoint": 9,
                "pressure1": 1080,
                "u": 249.6,
                "pressure2": 830.4,
                "blows": 4
            },
            {
                "elevation": 890.1,
                "sample_no": "S-06",
                "uscs": "ML",
                "weight": 122.2,
                "depth_to_top": 10,
                "depth_to_bottom": 12,
                "depth_to_midpoint": 11,
                "pressure1": 1344.5,
                "u": 374.4,
                "pressure2": 970.1,
                "blows": 14
            },
            {
                "elevation": 888.1,
                "sample_no": "S-07",
                "uscs": "ML",
                "weight": 120,
                "depth_to_top": 12,
                "depth_to_bottom": 14,
                "depth_to_midpoint": 13,
                "pressure1": 1560,
                "u": 499.2,
                "pressure2": 1060.8,
                "blows": 8
            },
            {
                "elevation": 886.1,
                "sample_no": "S-08",
                "uscs": "MH",
                "weight": 120,
                "depth_to_top": 14,
                "depth_to_bottom": 16,
                "depth_to_midpoint": 15,
                "pressure1": 1800,
                "u": 624,
                "pressure2": 1176,
                "blows": 9
            },
            {
                "elevation": 884.1,
                "sample_no": "S-09",
                "uscs": "PWR",
                "weight": 140,
                "depth_to_top": 16,
                "depth_to_bottom": 17.8,
                "depth_to_midpoint": 16.9,
                "pressure1": 2366,
                "u": 742.6,
                "pressure2": 1623.4,
                "blows": 39
            }
        ]
    }
]